[WIP] Add Supertokens Auth
timothymiller/t4-app pull request #106
Opened 2023-11-10 06:06 UTC by anku255

This PR adds [Supertokens](https://supertokens.com/) auth to the t4-app replacing Supabase. This PR is still a work in progress as OAuth is still unimplemented.

2023-11-10 07:54 UTC, rishabhpoddar requested changes

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/utils/supertokens/SessionAuth.ts
> +      return {
we also want to check for claim validations.

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/utils/supertokens/nativeConfig.ts
> +import { SuperTokensConfig } from 'supertokens-web-js/lib/build/types'
do not import from build

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/utils/supertokens/nativeConfig.ts
> +              // We are overriding the XMLHTTPRequest interceptor as it was causing issues and the fetch interceptor works fine
ideally we don't want to do this.

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/utils/supertokens/webConfig.ts
> +      },
not required.

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/features/sign-up/screen.tsx
> -  const handleOAuthSignInWithPress = async (provider: Provider) => {
need to add oauth login.

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/features/password-reset/screen.tsx
>        console.log('Password reset request failed', error)
```suggestion
```

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/features/password-reset/update-password/screen.tsx
> +    try {
handle deep links for this.

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/features/password-reset/update-password/screen.tsx
> +    try {
https://supertokens.com/docs/thirdpartyemailpassword/custom-ui/forgot-password#changing-the-password-reset-link

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/features/password-reset/update-password/screen.tsx
> +    try {
for native, you can use:
```
curl --location --request POST 'http://localhost:3001/auth/user/password/reset' \
--header 'rid: thirdpartyemailpassword' \
--header 'Content-Type: application/json; charset=utf-8' \
--data-raw '{
  "method": "token",
  "formFields": [
    {
      "id": "password",
      "value": "newPass123"
    }
  ],
  "token": "ZTRiOTBjNz...jI5MTZlODkxw"
}'
```

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/app/features/password-reset/update-password/screen.tsx
> +      console.log('Password update request failed', err)
remove console log

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/getSessionFromContext.ts
> +    return undefined
we need to handle all errors here: https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/sessions/session-verification-in-api/get-session#building-your-own-custom-middleware

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/getSessionFromContext.ts
> +  const userContext = makeDefaultUserContextFromAPI(request)
```suggestion
```

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/getSessionFromContext.ts
> +    const session = await getSession(request, response, options, userContext)
```suggestion
    const session = await getSession(request, response, options)
```

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/getSessionFromContext.ts
> +import { makeDefaultUserContextFromAPI } from 'supertokens-node/lib/build/utils'
no imports from build

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/getSessionFromContext.ts
> +    console.log('Got an error while verifying session: ', err)
```suggestion
```

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/hono.ts
> +import { BaseRequest, BaseResponse } from 'supertokens-node/lib/build/framework'
we don't want to import from build

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/middleware.ts
> +import { makeDefaultUserContextFromAPI } from 'supertokens-node/lib/build/utils'
```suggestion
```

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/middleware.ts
> +
use the custom framework middleware

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/types.ts
> +export type Bindings = {
you can delete this

2023-11-10 07:54 UTC, rishabhpoddar commented on packages/api/src/supertokens/config.ts
> +    connectionURI: "https://try.supertokens.com",
you need to use the env var

2023-11-10 07:54 UTC, rishabhpoddar commented on package.json
>      "@babel/runtime": "^7.23.2",
remove the bun.lockb

2023-11-10 07:54 UTC, rishabhpoddar commented on apps/expo/app/supertokens/LockFactory.ts
> +class Lock {
these need to be deleted

2023-11-10 07:54 UTC, rishabhpoddar commented on apps/expo/app/supertokens/LockFactory.ts
> +class Lock {
the whole supertokens folder

2023-11-10 07:54 UTC, rishabhpoddar commented on apps/expo/package.json
> +    "react-native-mmkv-storage": "^0.9.1",
this should not be used

2023-11-10 07:54 UTC, rishabhpoddar commented on apps/next/pages/_app.tsx
> +  }, [])
remove

2023-11-13 07:54 UTC, anku255 commented on packages/app/utils/supertokens/WindowHandler.ts
> +export function windowHandler(original) {
Moved these to `expo/app/supertokens` to make it clear that these are only intended for the expo app.

2023-11-13 11:10 UTC, anku255 commented on packages/app/utils/supertokens/CookieHandler.ts
> +  async setCookie(cookieString: string): Promise<void> {
It is not possible to set more than one cookie by using `document.cookie = 'some string'`.  However, I did refactor some of the code taking some inspiration from the above implementation.

2023-11-27 11:28 UTC, anku255 commented on packages/app/utils/supertokens/SessionAuth.ts
> +      return {
This is not needed anymore as I am no longer overriding the `Session` recipe.

2023-11-27 11:28 UTC, anku255 commented on packages/app/features/sign-up/screen.tsx
> -  const handleOAuthSignInWithPress = async (provider: Provider) => {
done

2023-11-27 11:29 UTC, anku255 commented on packages/api/src/supertokens/config.ts
> +    connectionURI: "https://try.supertokens.com",
done

2023-11-28 19:22 UTC, rishabhpoddar commented on packages/api/src/supertokens/hono.ts
> +    // TODO: Figure out how to handle allowDuplicateKey
TODO

2023-11-28 19:23 UTC, rishabhpoddar commented on packages/api/src/supertokens/hono.ts
> +    }[sameSite] as 'Strict' | 'Lax' | 'None'
why is it required to upper case it?

2023-11-28 19:41 UTC, rishabhpoddar commented on packages/app/utils/supertokens/SessionAuth.ts
> +      return {
You still need to check for claim validators in the useSession context.

2023-11-28 19:48 UTC, rishabhpoddar requested changes

2023-11-28 19:48 UTC, rishabhpoddar commented on packages/app/features/sign-in/screen.tsx
> +        replace('/')
Im a little confused about redirecting to `/`. There are cases where we are redirecting to `/` even if the user is not logged in (for example in reset password flow), but here we are also redirecting to `/`. 

That being said, we should extract the `/` into two variable:
- Login UI (also known as websiteBasePath in our backend and pre built UI SDK)
- Post login UI (where we will redirect the user to from here)

This way, if users want to change where the login UI is shown, they can do so easily.

2023-11-29 04:27 UTC, rishabhpoddar requested changes

2023-11-29 04:27 UTC, rishabhpoddar commented on packages/app/features/sign-in/screen.native.tsx
>        }
else, you need to show some sort of error.

2023-11-29 04:27 UTC, rishabhpoddar commented on packages/app/features/sign-in/screen.native.tsx
> +      const authorizationUrlRes: {
please test sign in with google using non test credentials.

2023-11-29 05:13 UTC, anku255 commented on .env.example
> +API_URL=http://localhost:8787
yes

2023-11-29 05:15 UTC, anku255 commented on apps/expo/app/supertokens/CookieHandler.ts
> +import { MMKV } from 'react-native-mmkv'
yes

2023-11-29 05:18 UTC, anku255 commented on apps/expo/app/supertokens/config.ts
> +    appName: 'T4 App',
done

2023-11-29 05:23 UTC, anku255 commented on apps/expo/app/supertokens/LockFactory.ts
> +    return this.lockStateMap[key] as LockState
Used a non-null assertion instead. In these cases TS isn't smart to infer the correct type.

2023-11-29 05:25 UTC, anku255 commented on packages/app/utils/trpc/index.tsx
>    const apiUrl = `${process.env.EXPO_PUBLIC_API_URL}`
`API_URL` is becoming `EXPO_PUBLIC_API_URL` in  the expo app. This file is only used in expo context.

2023-11-29 05:27 UTC, anku255 commented on apps/next/supertokens/config.ts
> +    appName: 'T4 App',
done

2023-11-29 05:28 UTC, anku255 commented on packages/app/features/oauth/screen.tsx
> +        // this can happen due to automatic account linking. Please see - supertokens account linking docs
done

2023-11-29 05:29 UTC, anku255 commented on packages/app/features/oauth/screen.tsx
> +  const [redirectTo] = useParam('redirectTo')
It is not required and is not being used currently. It is just there in case someone wants to use it. For the boilterplate, we are always redirecting to `/` after login.

2023-11-29 05:32 UTC, anku255 commented on packages/app/features/oauth/screen.tsx
> +  }, [provider])
It is called only once with provider. I have tested it several times, there are no issues.

2023-11-29 05:33 UTC, anku255 commented on apps/next/supertokens/config.ts
> +import { sessionEventManager } from 'app/utils/supertokens/SessionEventManager'
done

2023-11-29 05:33 UTC, anku255 commented on apps/expo/app/supertokens/config.ts
> +import { getApiUrl } from 'app/utils/trpc'
done

2023-11-29 05:33 UTC, anku255 commented on packages/api/src/supertokens/config.ts
> +import SuperTokens from 'supertokens-node'
done

2023-11-29 05:33 UTC, anku255 commented on packages/app/features/sign-in/screen.native.tsx
> +      toast.show('Apple OAuth is not supported yet.')
It will be done in a different PR

2023-11-29 05:34 UTC, anku255 commented on packages/app/features/home/screen.tsx
> +  const { doesSessionExist, accessTokenPayload, userId } = useSession()
done

2023-11-29 05:35 UTC, anku255 commented on packages/app/features/password-reset/screen.tsx
> +                  'X-Platform': isAndroid ? 'android' : isIos ? 'ios' : 'web',
done

2023-11-29 05:36 UTC, anku255 commented on packages/app/features/password-reset/screen.tsx
> +        toast.show('No account exists with this email.')
Updated the error message.

2023-11-29 05:37 UTC, anku255 commented on packages/app/features/password-reset/screen.tsx
> +        push('/')
That was the current behavior.

2023-11-29 05:38 UTC, anku255 commented on packages/app/features/password-reset/update-password/screen.tsx
> +      const res = (await fetch(`${API_URL}/api/auth/user/password/reset`, {
yes, it is not possible to pass the token in that function.

2023-11-29 05:38 UTC, anku255 commented on packages/app/features/password-reset/update-password/screen.tsx
> +          rid: rid ?? 'thirdpartyemailpassword',
done

2023-11-29 05:39 UTC, anku255 commented on packages/app/features/password-reset/update-password/screen.tsx
> +        push('/')
I just replicated the current behavior.

2023-11-29 05:40 UTC, anku255 commented on packages/app/features/password-reset/update-password/screen.tsx
> +  const handlePasswordUpdateWithPress = async (password: string) => {
Used in this [file](https://github.com/anku255/t4-app/blob/supertokens-auth/packages/ui/src/PasswordReset.tsx)

You were not able to find it because it has been renamed to `handleWithPress` while passing it as prop.

2023-11-29 05:40 UTC, anku255 commented on packages/app/features/sign-in/screen.native.tsx
> +              pkceCodeVerifier: authorizationUrlRes.pkceCodeVerifier,
Need this for Discord OAuth.

2023-11-29 05:42 UTC, anku255 commented on packages/app/features/sign-in/screen.tsx
> +      toast.show('Apple OAuth is not supported yet.')
will be handled in a different PR.

2023-11-29 05:42 UTC, anku255 commented on packages/app/utils/trpc/index.web.ts
>            url: `${process.env.NEXT_PUBLIC_API_URL}/trpc`,
yeah it does.

2023-11-29 05:42 UTC, anku255 commented on packages/api/src/supertokens/config.ts
> +      appName: 'T4 App',
done

2023-11-29 05:43 UTC, anku255 commented on packages/api/src/supertokens/hono.ts
> +    }[sameSite] as 'Strict' | 'Lax' | 'None'
That's how Hono expects it.

2023-11-29 05:45 UTC, anku255 commented on packages/app/features/sign-in/screen.tsx
> +        replace('/')
Just kept the existing behavior to be consistent with Supabase

2023-11-29 05:46 UTC, anku255 commented on packages/app/features/sign-in/screen.native.tsx
> +        // window.alert("Email password combination is incorrect.")
done

2023-11-29 05:47 UTC, anku255 commented on packages/app/features/sign-up/screen.native.tsx
> +              pkceCodeVerifier: authorizationUrlRes.pkceCodeVerifier,
Need this for Discord OAuth and it doesn't break Other OAuth as it is going be undefined.

2023-11-29 05:50 UTC, anku255 commented on packages/app/utils/supertokens/hooks/useSession.tsx
> +          })
good catch. We need to handle this in both the places (catch block and if(!sessionExists))

2023-11-29 05:50 UTC, anku255 commented on packages/app/utils/supertokens/hooks/useAuthRedirect.ts
> +        router.replace('/')
just kept the default behavior to be consistent.

2023-11-29 05:50 UTC, anku255 commented on packages/app/utils/trpc/index.tsx
>            url: `${getApiUrl()}/trpc`,
yes

2023-11-29 05:51 UTC, anku255 commented on packages/api/src/supertokens/middleware.ts
> +      console.log('err', err)
done

2023-11-29 05:52 UTC, anku255 commented on packages/api/src/supertokens/middleware.ts
> +          return new Response('Authentication required', {
done

2023-11-29 05:54 UTC, anku255 commented on packages/api/src/worker.ts
> +  await next()
No.. in fact you don't want to use the return statement. There could be statements after `await next()` as well and they will be executed after the request is processed. See [this](https://hono.dev/guides/middleware#execution-order) for more info.

2023-11-29 05:54 UTC, anku255 commented on packages/api/src/worker.ts
>      allowMethods: ['POST', 'GET'],
done

2023-11-29 06:23 UTC, anku255 commented on packages/api/src/supertokens/config.ts
> +      Session.init(), // initializes session features
Added and tested both of them. Works perfectly fine.

2023-11-29 06:23 UTC, anku255 commented on packages/app/features/sign-in/screen.native.tsx
>        }
what do you mean?

2023-11-29 07:53 UTC, anku255 commented on packages/api/src/supertokens/config.ts
> +      ThirdParty.init({
done

2023-11-29 13:33 UTC, anku255 commented on .env.example
> +GOOGLE_CLIENT_SECRET=
done for google. Will do it for Apple when I add Apple OAuth.

2023-11-29 13:38 UTC, anku255 commented on apps/expo/app/supertokens/WindowHandler.ts
> +        // We are returning a dummy hostname to make supertokens happy
done

2023-11-29 13:43 UTC, anku255 commented on apps/expo/app/supertokens/config.ts
> +              // We are overriding the XMLHTTPRequest interceptor as it was causing issues and the fetch interceptor works fine
didn't get you.. Did you mean add the instructions from [here](https://supertokens.com/docs/thirdpartyemailpassword/custom-ui/handling-session-tokens#for-react-native)?

2023-11-29 13:43 UTC, anku255 commented on apps/next/supertokens/config.ts
> +    ThirdParty.init(),
done

2023-11-29 13:45 UTC, anku255 commented on packages/app/features/password-reset/screen.tsx
>        })
done

2023-11-29 13:47 UTC, anku255 commented on packages/app/features/sign-up/screen.native.tsx
> +  const handleOAuthSignUpWithPress = async (provider: 'google' | 'apple' | 'discord') => {
The implementation is likely to change once we use specific libraries for native. This is why I kept it separate.

2023-11-29 13:47 UTC, anku255 commented on packages/app/utils/supertokens/SessionEventManager.ts
> +  accessTokenPayload: any
done

2023-11-29 13:48 UTC, anku255 commented on packages/api/src/supertokens/hono.ts
> +    return this.context.req.json()
Not needed anymore

2023-11-29 13:48 UTC, anku255 commented on packages/api/src/supertokens/hono.ts
> +    this.context.req.formData()
Not needed anymore

2023-11-29 13:48 UTC, anku255 commented on packages/api/src/supertokens/hono.ts
> +export class STHonoRequest {
Not needed anymore

2023-11-29 13:48 UTC, anku255 commented on packages/api/src/supertokens/middleware.ts
> +        getJSONBody: () => c.req.json(),
Not needed as the `BaseRequest` is doing the caching after the latest release.

2023-11-29 13:48 UTC, anku255 commented on packages/api/src/supertokens/middleware.ts
> +    }
done

2023-11-29 13:49 UTC, anku255 commented on packages/api/src/supertokens/middleware.ts
> +      return await next()
done

2023-11-30 16:09 UTC, rishabhpoddar requested changes

2023-12-01 17:54 UTC, anku255 commented on packages/api/src/supertokens/middleware.ts
> +    const stMiddleware = customMiddleware<Context>((c) => request)
That `PreParsed` request is also used later in the same function, that is why I am creating it above.

2023-12-01 17:55 UTC, anku255 commented on packages/app/features/sign-in/screen.native.tsx
> +      const authorizationUrlRes: {
done.

2023-12-04 05:10 UTC, rishabhpoddar commented on .env.example
> +API_URL=http://localhost:8787
ok

2023-12-04 05:10 UTC, rishabhpoddar commented on apps/expo/app/supertokens/CookieHandler.ts
> +import { MMKV } from 'react-native-mmkv'
ok

2023-12-04 05:10 UTC, rishabhpoddar commented on apps/expo/app/supertokens/LockFactory.ts
> +    return this.lockStateMap[key] as LockState
ok

2023-12-04 05:12 UTC, rishabhpoddar commented on apps/expo/app/supertokens/WindowHandler.ts
> +        // We are returning a dummy hostname to make supertokens happy
ok

2023-12-04 05:15 UTC, rishabhpoddar commented on apps/next/supertokens/config.ts
> +    appName: 'T4 App',
ok

2023-12-04 05:18 UTC, rishabhpoddar commented on packages/app/features/oauth/utils.native.ts
> +  }
need to handle other status return types as well. Like `SIGN_IN_UP_NOT_ALLOWED` etc (like how it's done in the web version)

2023-12-04 05:18 UTC, rishabhpoddar commented on packages/app/features/oauth/screen.tsx
> +  const [redirectTo] = useParam('redirectTo')
ok

2023-12-04 05:19 UTC, rishabhpoddar commented on apps/expo/app/supertokens/config.ts
> +import { getApiUrl } from 'app/utils/trpc'
ok

2023-12-04 05:19 UTC, rishabhpoddar commented on packages/api/src/supertokens/config.ts
> +import SuperTokens from 'supertokens-node'
ok

2023-12-04 05:21 UTC, rishabhpoddar commented on packages/app/features/password-reset/screen.tsx
> +        push('/')
ok

2023-12-04 05:22 UTC, rishabhpoddar commented on packages/app/features/password-reset/update-password/screen.tsx
> +      const res = (await fetch(`${API_URL}/api/auth/user/password/reset`, {
ok

2023-12-04 05:26 UTC, rishabhpoddar commented on packages/app/utils/supertokens/SessionEventManager.ts
> +  accessTokenPayload: any
ok

2023-12-04 05:26 UTC, rishabhpoddar commented on packages/app/utils/supertokens/hooks/useSession.tsx
> +          })
ok

2023-12-04 05:26 UTC, rishabhpoddar commented on packages/app/utils/supertokens/hooks/useAuthRedirect.ts
> +        router.replace('/')
ok

2023-12-04 05:26 UTC, rishabhpoddar commented on packages/app/utils/trpc/index.tsx
>            url: `${getApiUrl()}/trpc`,
ok

2023-12-04 05:26 UTC, rishabhpoddar commented on packages/app/utils/trpc/index.web.ts
>            url: `${process.env.NEXT_PUBLIC_API_URL}/trpc`,
ok

2023-12-04 05:27 UTC, rishabhpoddar commented on packages/api/src/supertokens/middleware.ts
> +        getJSONBody: () => c.req.json(),
ok

2023-12-04 05:27 UTC, rishabhpoddar commented on packages/api/src/supertokens/middleware.ts
> +      console.log('err', err)
ok

2023-12-04 05:28 UTC, rishabhpoddar commented on packages/api/src/worker.ts
>      allowMethods: ['POST', 'GET'],
ok

2023-12-04 05:30 UTC, rishabhpoddar commented on packages/app/features/sign-in/screen.native.tsx
>        }
ignore this question. It's all fine.

2023-12-04 06:57 UTC, rishabhpoddar approved these changes

2023-12-04 06:57 UTC, rishabhpoddar commented on packages/app/features/oauth/utils.native.ts
> +  }
ok

2023-12-13 04:53 UTC, timothymiller commented
LGTM!

2023-12-13 04:53 UTC, merged